name: Deploy to App Engine

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploying
      uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: ${{secrets.APP_ENGINE_PROJECT_NAME}}
        APPLICATION_CREDENTIALS: ${{secrets.GCLOUD_AUTH}}
      with:
        args: app deploy app.yaml
